### ISSUE TITLE
@inbook or @incollection?

### ISSUE THREAD

**Issue by chrisroadmap** [openclimatedata/ipcc-bibtex#20]
WG1 AR6 citations are @inbook, WG3 AR6 are @incollection.

Should they be consistent? and is there a difference, in practice?

**Comment by chrisroadmap** [comment]
I think @incollection might be preferred. I'm using vanilla BibTeX and I get the following warning with @inbook:

```
This is BibTeX, Version 0.99d (TeX Live 2021)
The top-level auxiliary file: main.aux
The style file: plainnat.bst
Database file #1: main.bib
Warning--can't use both author and editor fields in Canadell2021
(There was 1 warning)
```

If you want I can update these and make a PR

**Comment by rgieseke** [comment]
Sounds good to me!

**Comment by rgieseke** [comment]
Done in #22
