### ISSUE TITLE
Reference type for Byers et al

### ISSUE THREAD

**Issue by GlenPetersCICERO** [openclimatedata/ipcc-bibtex#26]
It seems Zotero did not understand the @dataset reference type for Byers et al.

**Comment by rgieseke** [comment]
Maybe we should use `@misc`. Seems `@dataset` is only available in BibLaTeX.

**Comment by jkikstra** [comment]
Fine with me.

**Comment by rgieseke** [comment]
Thanks both, fixed in https://github.com/openclimatedata/ipcc-bibtex/commit/2efda6826ee581f5fe89a7a388cdefdd4b7fc725
