### ISSUE TITLE
FAR, SAR, TAR, AR5 html cleanup; add FAR, SAR and TAR Chapter refs

### ISSUE THREAD

**Issue by durack1** [openclimatedata/ipcc-bibtex#36]
I have completed the following:
- [x] Added Ch3/Cubasch, Ch4/Gates to `far-wg-i.bib`
- [x] Cleaned up header in `far-wg-i.html`, `sar-wg-i.html`, `tar-wg-i.html`, and `ar5-wg-iii.html`
- [x] Cleaned up incorrect header references (above) in `Makefile`
- [x] Added Ch1/Trenberth, Ch3/Nicholls, Ch4/Dickinson and Ch5/Gates to `sar-wg-i.bib`
- [x] Added Ch8/McAvaney to `tar-wg-i.bib`
- [x] Run `Makefile` (`bibtex2html` over updated `*.bib` files)

**Comment by durack1** [comment]
@rgieseke can you provide `write` privileges to me for this repo so I can push a PR? thanks.

**Comment by rgieseke** [comment]
@durack1 you can 'fork' this repo and create a PR from your fork

**Comment by durack1** [comment]
@rgieseke, thanks; I had intentionally not created a fork, as I consider this a one-time sync and update.

I happily provide this once-off contribution, meeting my current citation needs. As repo update frequency is VERY low, I'm unlikely to pay ongoing attention to this repo, so would likely delete a fork soon thereafter

**Comment by rgieseke** [comment]
Sure, I think that's a typical pattern, I do that myself too to keep the list of repos on my account manageable.

I appreciate your contribution to this collection!

**Comment by durack1** [comment]
@rgieseke done #37 should have the changes that I needed (FAR, SAR, TAR), plus a little handspun cleanup of the Makefile that generates the HTML files - I couldn't get bibtex2html working (don't much like pip), so gave up before minting the new htmls - I hope a maintainer of the repo has a handy conda env that could whip up these files trivially after #37 is merged.

I delete my fork immediately after this is pulled across.

**Comment by rgieseke** [comment]
Updated with bib2html on the main branch. Thank you for your contribution and attention to detail by fixing the incorrect title tags!

**Comment by durack1** [comment]
@rgieseke my pleasure, glad to see these updates in place!
